apiVersion: v1
kind: Secret
metadata:
  name: api-secret
type: Opaque
stringData:
  ConnectionStrings__Default: "${DB_CONNECTION_STRING}"
  ConnectionStrings__Redis: "${REDIS_CONNECTION_STRING}"
  Kafka__BootstrapServers: "${KAFKA_BOOTSTRAP_SERVERS}"
  Kafka__GroupId: "${KAFKA_GROUP_ID}"
  Jwt__Secret: "${JWT_SECRET}"
  Jwt__ExpiresInMinutes: "${JWT_EXPIRES_IN_MINUTES}"
  Cloudinary__CloudName: "${CLOUDINARY_CLOUD_NAME}"
  Cloudinary__ApiKey: "${CLOUDINARY_API_KEY}"
  Cloudinary__ApiSecret: "${CLOUDINARY_API_SECRET}"
  Gemini__ApiKey: "${GEMINI_API_KEY}"
  Cohere__ApiKey: "${COHERE_API_KEY}"
  Cohere__Url: "${COHERE_URL}"
  Mistral__ApiKey: "${MISTRAL_API_KEY}"
  Cloudflare__ApiToken: "${CLOUDFLARE_API_TOKEN}"
  Cloudflare__AccountId: "${CLOUDFLARE_ACCOUNT_ID}"
  OpenRouter__ApiKey: "${OPENROUTER_API_KEY}"
  Groq__ApiKey: "${GROQ_API_KEY}"
  Cerebras__ApiKey: "${CEREBRAS_API_KEY}"
  Pollinations__ApiKey: "${POLLINATIONS_API_KEY}"
  Smtp__Host: "${SMTP_HOST}"
  Smtp__Port: "${SMTP_PORT}"
  Smtp__Username: "${SMTP_USERNAME}"
  Smtp__Password: "${SMTP_PASSWORD}"
  Smtp__From: "${SMTP_FROM}"
